registerOutputEvent(GameConnection,lockAvatar,"",1);
registerOutputEvent(GameConnection,unlockAvatar,"",1);
registerOutputEvent(GameConnection,setHeadSmiley,"list BrownSmiley 0 ChefSmiley 1 KleinerSmiley 2 Male07Smiley 3 Orc 4 AdamSavage 5 Jamie 6 AsciiTerror 7 MemeBlockMongler 8 MemeCats 9 MemeDesu 10 MemeGrinMan 11 MemeHappy 12 MemePBear 13 MemeYaranika 14 SmileyBlonde 15 SmileyCreepy 16 SmileyEvil1 17 SmileyEvil2 18 SmileyFemale1 19 SmileyOld 20 SmileyPirate1 21 SmileyPirate2 22 SmileyPirate3 23 SmileyRedBeard 24 SmileyRedBeard2 25",0);
registerOutputEvent(GameConnection,setHeadColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setHatType,"list Helmet 0 PointyHelmet 1 FlareHelmet 2 ScoutHat 3 Bicorn 4 Cophat 5 Knithat 6 None 7");
registerOutputEvent(GameConnection,setHatColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setHatAccentType,"list Plume 0 Triplume 1 SeptPlume 2 None 3");
registerOutputEvent(GameConnection,setHatAccentColor,"list Plume 0 Triplume 1 SeptPlume 2	paintColor paintColor");
registerOutputEvent(GameConnection,setBodyColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setBodyDecal,"list Alyx 0 Archer 1 Chef 2 DKnight 3 DrKleiner 4 HCZombie 5 Knight 6 LinkTunic 7 Hoodie 8 Medieval-Eagle 9 Medieval-Lion 10 Medieval-Rider 11 Medieval-Tunic 12 Medieval-YARLY 13 Meme-Mongler 14 Mod-Army 15 Mod-DareDevil 16 Mod-Pilot 17 Mod-Prisoner 18 Mod-Suit 19 Space-Nasa 20 Space-New 21 Space-Old 22 Worm-Engineer 23 Worm-Sweater 24 None 25");
registerOutputEvent(GameConnection,setBodyType,"list Male 0 Female 1");
registerOutputEvent(GameConnection,setPantsColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setPantsType,"list Male 0 Female 1");
registerOutputEvent(GameConnection,setRightArmColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftArmColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftHandColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftHandType,"list Hook 0 Hand 1");
registerOutputEvent(GameConnection,setRightHandColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setRightHandType,"list Hook 0 Hand 1");
registerOutputEvent(GameConnection,setRightShoeColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftShoeColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setRightSkiColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftSkiColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setRightPegColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftPegColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setLeftShoeType,"list Shoe 0 Ski 1 Peg 2");
registerOutputEvent(GameConnection,setRightShoeType,"list Shoe 0 Ski 1 Peg 2");
registerOutputEvent(GameConnection,setPackType,"list Armor 0 Bucket 1 Cape 2 Pack 3 Quiver 4 Tank 5 None 6");
registerOutputEvent(GameConnection,setPackColor,"paintColor paintColor");
registerOutputEvent(GameConnection,setCustomAvatar,"string 100 100");
registerOutputEvent(GameConnection,setDefaultAvatar);


